apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - service.yaml

images:
  - name: splitity/splitity-web
    newName: splitity/production-splitity-web
    newTag: latest
  - name: splitity/splitity-backend
    newName: splitity/splitity-backend
    newTag: latest

nameSuffix: -production
