github:
  app_id:
  client_id:
  client_secret:
  webhook_secret:
  private_key:
redis:
  uri:
postgres:
  host:
  port:
  username:
  password:
frontend_web:
  url:
mixpanel:
  token:
sentry:
  dsn:
cors:
  allowed_origins:
encryption_key:
