FROM node:12.14.1-alpine

ARG REACT_APP_FIREBASE_KEY
ARG REACT_APP_FIREBASE_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_APP_ID
ARG GITHUB_APP_NAME
ARG BACKEND_API_URL
ARG MIXPANEL_TOKEN
ARG SENTRY_DSN
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_RELEASE
ARG GITHUB_APP_CLIENT_ID
ARG WEB_URL

WORKDIR /web

COPY web/ /web/
COPY yarn.lock /yarn.lock
COPY package.json /package.json

RUN yarn install
RUN yarn build

# Delete source maps
RUN rm public/*.map

EXPOSE 8080

CMD yarn serve
