version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - working_directory: split-my-prs
    steps:
      - checkout
      - restore_cache:
        keys:
        - yarn-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
        key: yarn-cache-v1-{{ checksum "package-lock.json" }}
        paths:
          - node_modules
      - run:
          name: Run jest unit tests
          command: yarn jest
          working_directory: ~/split-my-prs/web
