version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/splitity
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-v4-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-cache-v4-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - web/node_modules
      - run:
          name: Run jest unit tests
          command: yarn jest --collectCoverage=true --ci --maxWorkers=1
          working_directory: web
      - store_artifacts:
          path: web/coverage
      - codecov/upload:
          file: web/coverage/*.json
          flags: frontend,unit

  backend_unit_tests:
    working_directory: ~/splitity
    docker:
      - image: circleci/ruby:2.7.0-node
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd backend
            sudo apt-get update
            sudo apt-get -y install cmake
      - restore_cache:
          keys:
            - rails-bundle-v1-{{ checksum "backend/Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd backend
            bundle check || bundle install
      - save_cache:
          key: rails-bundle-v1-{{ checksum "backend/Gemfile.lock" }}
          paths:
            - backend/vendor/bundle
      - run:
          name: Setup database
          command: |
            cd backend
            bin/rails db:setup
      - run:
          name: Run rails unit tests
          command: |
            cd backend
            DISABLE_SPRING=1 CI=true bin/rails test
      - store_artifacts:
          path: backend/coverage
      - codecov/upload:
          file: backend/coverage/.resultset.json
          flags: backend,unit

  build_web:
    working_directory: ~/splitity
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Web Docker image
          command: >-
            docker build
            --file "web.Dockerfile"
            --tag "splitity/${BUILD_ENV}-splitity-web:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}"
            --build-arg REACT_APP_FIREBASE_KEY="${REACT_APP_FIREBASE_KEY}"
            --build-arg REACT_APP_FIREBASE_DOMAIN="${REACT_APP_FIREBASE_DOMAIN}"
            --build-arg REACT_APP_FIREBASE_PROJECT_ID="${REACT_APP_FIREBASE_PROJECT_ID}"
            --build-arg REACT_APP_FIREBASE_APP_ID="${REACT_APP_FIREBASE_APP_ID}"
            --build-arg GITHUB_APP_NAME="${GITHUB_APP_NAME}"
            --build-arg BACKEND_API_URL="${BACKEND_API_URL}"
            --build-arg MIXPANEL_TOKEN="${MIXPANEL_TOKEN}"
            .
      - run:
          name: Login to docker hub
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
      - run:
          name: Push Web Docker image
          command: docker push "splitity/${BUILD_ENV}-splitity-web:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}"

  deploy_web:
    working_directory: ~/splitity
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo snap install kubectl --classic
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
            sudo snap install doctl
            doctl auth login --access_token "$DIGITAL_OCEAN_ACCESS_TOKEN"
            doctl kubernetes cluster kubeconfig "splitity-${BUILD_ENV}-k8s-cluster"
      - run:
          name: Setup K8s secrets
          command: |
            kubectl create secret docker-registry regcred --docker-username="$DOCKER_LOGIN" --docker-password="$DOCKER_PASSWORD"
      - run:
          name: Update image tag
          command: |
            cd splitity/infra/k8s/dev
            kustomize edit set image "splitity/splitity-web=splitity/${BUILD_ENV}-splitity-web:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}"
      - run:
          name: Deploy to K8s cluster
          command: |
            cd splitity/infra/k8s/dev
            kubectl apply -k .

workflows:
  unit_tests:
    jobs:
      - build
      - backend_unit_tests
  deploy_dev:
    jobs:
      - hold:
          type: approval
      - build_web:
          context: splitity-dev-web
          requires:
            - hold
      - deploy_web:
          context: splitity-dev-web
          requires:
            - build_web
