version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/split-my-prs
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-v4-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-cache-v4-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - web/node_modules
      - run:
          name: Run jest unit tests and collect codecov coverage reports
          command: yarn jest --collectCoverage=true --ci --maxWorkers=1
          working_directory: web
      - store_artifacts:
          path: web/coverage
      - codecov/upload:
          file: web/coverage/*.json
          flags: frontend,unit
  backend_build:
    working_directory: ~/split-my-prs
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - run:
          name: Update bundler to v2
          command: |
            sudo gem update --system
            bundle update --bundler
      - run:
          name: Install dependencies
          command: bundle install --deployment --gemfile='backend/Gemfile'
      - run:
          name: Setup database
          command: backend/bin/rails db:setup
      - run:
          name: Run rails unit tests
          command: backend/bin/rails test
workflows:
  unit_tests:
    jobs:
      - build
      - backend_build
