apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splitity
  template:
    metadata:
      labels:
        app: splitity
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: splitity
          image: clintoon/splitity-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
