apiVersion: autoscaling/v2beta2
kind: Deployment
metadata:
  name: splitity-web
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  selector:
    matchLabels:
      app: splitity-web
  template:
    metadata:
      labels:
        app: splitity-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: splitity-web
          image: splitity/splitity-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: Deployment
metadata:
  name: splitity-backend-api
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  selector:
    matchLabels:
      app: splitity-backend-api
  template:
    metadata:
      labels:
        app: splitity-backend-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: splitity-backend-api
          image: splitity/splitity-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: rails_master_key
---
apiVersion: autoscaling/v2beta2
kind: Deployment
metadata:
  name: splitity-backend-sidekiq
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  selector:
    matchLabels:
      app: splitity-backend-sidekiq
  template:
    metadata:
      labels:
        app: splitity-backend-sidekiq
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: splitity-backend-sidekiq
          image: splitity/splitity-backend:latest
          imagePullPolicy: Always
          command: ['/bin/bash', '-c', 'remote_syslog && bundle exec sidekiq']
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: rails_master_key
