apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: splitity-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: splitity-web
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: splitity-backend-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: splitity-backend-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: splitity-backend-sidekiq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: splitity-backend-sidekiq
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
