apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - service.yaml

images:
  - name: clintoon/splitity-web
    newName: clintoon/splitity-web-dev
    newTag: latest

nameSuffix: -dev
